---
title: "Assignment2"
author: "Nitij"
date: "22 October 2015"
output: html_document
bibliography: Biblio.bib
---

Brazil, Russia, India, China and South Africa form a conglomerate of the worldÅLs fastest economies acting as major engines of global growth. What role did ICT developments play in the exponential boom of these nations and to what extend did investments in ICT determine this unprecedented economic growth?

Nowadays, communication and information technologies (ICT) are an essential tool in every society and economy, transforming ways social and personal interaction happens, enabling global cooperation between businesses trough ÅgThe Internet of ThingsÅh, bustling industries, spurred by entrepreneurship and supported by a variety of multinational enterprises and helping governments to broaden citizen services and improving their delivery. 

The pace, at which countries outside of the advanced economies are adopting the Internet, is much faster than that of advanced economies[@nottebohm2012online].According to a study conducted by BCG, by 2016, there will be 3 billion Internet users globally, almost half of the worldÅfs population. The Internet economy will reach 4.2 trillion dollars in the G-20 countries[@dean2012internet].The global Internet is seen as major driving force for the further development of communication networks. The widespread introduction of mobile and wireless communication more than 20 years ago is providing access to global communication to an ever-increasing number of users, which helps emerging economies to develop and drastically grow. Developing G20 countries have already reached 800 million Internet users, social networks reach 80% of users in both developed and developing countries. Mobile devices, smartphones and tablets will account for 4 out of 5 broadband connections by 2016 [@dean2012internet]. In our analysis we will focus on the effects that the aforementioned variables (Mobile usage, internet access and wireless communication) have on GDP in BRICS nations. The dataset is taken from the World Bank. The purpose of this research is to quantifiably measure the relationship between technological advancement and economic growth explained by GDP. Our research conclude that
Most economists agree that innovation is one of the key determinants explaining long-term economic growth. Moreover, quantitative studies have shown that there is a statistical link between innovation and increased standards of living. ÅgFor emerging markets to grow and expand output they can either increase the volume of input or introduce technology to help workers use existing levels of input more productivelyÅh[@blalock2008welfare]. The BRICS were less impacted by the financial and economic crisis spreading in 2008 in all major developed economies. These nations represent 3 billion people and combined GDP of 26 trillion dollars. As a matter of fact, Ågit is the third giant after US ad EUÅh[@stone2006competitive] . It is wisely acknowledged that growth rates for these emerging economies have been far above average during the last decade, and have exceeded those of the more advanced countries. Consequently these four countries are driving most of the worldÅLs GDP growth.
In 2010, BRICS accounted for 13% of global demand with spending of 328 billion euros in ICT (EITO, 2010). Therefore they play as major players as consumers but also producer of ICT goods and services. China, for instance, has become the worldÅfs largest producer of ICT products. We consider ICT as main driver of economic growth due to its unique multiplier effect: 1) it offers new goods and services for consumers, (stimulates Final demand on the supply side); 2) ICT supply also increases the demand for the output of other industries( Demand multiplier); 3) ICT supply creates new opportunities for production in other industries, ( Supply Multiplier). Our hypothesis is that broad access to the internet and mobile technologies is correlated with higher growth in per capita GDP. 

Defining ICT
ÅgInformation and Communication Technology refers to multiple types of communication networks and technologies, combining manufacturing and services industries whose production fulfills or enables the function of information processing and communication by electronic means, including transmission and displays. It highly effects technological progress, output and productivity growth. Its output can be measured directly, trough its contribution to output, employment or productivity growth or indirectly as a source of technological change affecting other parts of the economyÅh (OECD, 2015). 

Definition ICT Investment
ÅgICT investment is defined as the acquisition of equipment and computer software that is used in production for more than one year. ICT has three components: information technology equipment (computers and related hardware); communications equipment; and software. Software includes acquisition of pre-packaged software, customized software and software developed in-house. This indicator is measured as a percentage of total non-residential gross fixed capital formation Åg(OECD, 2015).

Defining BRIC+S
The term BRIC was initially coined by Jim OÅfNeil (former Goldman Sachs chief economist) in 2001, to refer to the High Growth economies of Brazil, Russia, India and China (Crowe, 2015). The BRIC would overtake the 6 largest western economies in terms of economic might and become the pillars of the 21st century economy. In 2011, the acronym bracketed with South Africa to make BRICS. 
Defining GDP
GDP: an estimate of the total value of goods and services produced in a country, it aims to best capture the true monetary value of an economy. The Office for National Statistics (ONS) defines GDP as Åg the sum total of the final output an economy produces.Åh 

The analysis is based on the following econometric equation: 
GDP= Labour+ICTcapital+NonICTcapital+...


As factors affecting our dependent variable and thus economic growth (GDP) we could look at standard economic models, the aggregate demand (AD)and the Long Run Aggregate Supply curves(LRAS).
(AD): AD= C+I+G+X-M consumption, investment, governemnt expenditures, net exports ( Exports ??? imports). 
What affects AD?
Interest Rates: lower interest rates make borrowing cheaper and should encourage firms to invest and consumers to spend. However, recently we faced a period of zero interest rates but due to low confidence and reluctant bankc, growth was still sluggish.
Consumer confidence: consumer and business confidence are central to economic growth. If consumers are confident about the future, they will borrow and spend. If pessimistic views the save and reduce spendings.
Asset Prices: Rising house proces create a positive effect. People can remortgage against rising value of their home encouraging consumers to spend. Are many people homeowners?
Real Wages: inflation should be lower than nominal wage to see rising incomes.
Value of Exchange Rate: if the home currency devaluates, exports become more competitive and imports more expensive. Increased demand of domestic goods and services. Depreciation causes inflation, but it can provide a boost in the short term to growth.
Banking sector: Key in determining investment and growth. If banks loose money and strop lending, it causes declined investments.

In the long run economic growth is determined by factors influencing growth in the Long Run Aggregate Supply(LRAS)
LRAS cab be influenced by:
Levels of infrasturcture: investing in roads, transportation and communication can help firms reduce costs and expand production. Without proper infrastructure it is difficult for firms to be competitive in the international market. Lack of infrastructure is often a factor holding back some developing economies.
Human Capital: the productivity of workers. Determined by levels of education, training and motivation. The more educated, the more sophisticates production processes can be.
Development of technology: ICT is not only one of the fastest growing industries, directly creating millions of jobs but also an important enabler of innovation and development.
1 job creation:
2 GDP growth: ie a 10% increase in broadband penetration is associated with a 1.4% increase in GDP growth in Highly growing markets. The doubling of mobile dara use caused by the increase in 3G connections boosts GDP growth b 0.5% globally. The internet accounts for 3.4% of overall GDP in some economies. Most of this effect is driven b ecommerce. ( people adveritsing and selling goods online).
Emergence of new services and industries: Numerous public services have become available online and trough mobile phones. The transition to cloud computing is one of the key trends to modernisation. Emergence of App Industry: Fb apps alone created over 182,00 jobs in 2011 and the aggregate value of Facebook app economy exceeds 12 billion dollars.
Workforce transformation: new ??? microworkÅg plattforms, developed by companies like oDesk, Amazon and Samasource help to divide tasks into small components that can then be outsorced to contract workers. Contractors are usually based in emerging economies. Companies are able to cut coast and get to qualified workforce. ICT also contributed to the rise of entrepreneurship, making it easier for self starters to access best practices, legal and regulatory information, marketing and investment resources.


#Reference
