---
title: "Impact of ICT on GDP growth in Developed, Developing and Emerging countries"
author: "Alessia and Nitij"
date: "20 November 2015"
output: html_document
---
# Impact of ICT on GDP growth in Developed, Developing and Emerging Countries

# Abstract 

This paper aims at analyzing the validity of the relationship between Information and Communication Technology (ICT) and economic development, expressed in terms of GDP growth. The study provides a cross-country view on the issue upon assessing the impact of ICT on economic growth for 54 countries from the developed, emerging and developing world. Our results show that even though the impact of ICT capital stock per capita is significant in the developed and emerging economies, it cannot be used to make generalizations for the developing countries.

# Introduction 

The information revolution and the extraordinary increase in the spreading of knowledge have given rise to a new era of knowledge and information, affecting directly economic, social, cultural and political activities of all regions of the world[@ogunsola2005information] 

For years, Information and Communication Technologies (ICT) has been identified as a key driver for improving living standards. These higher living standards often correlate with productivity growth[@timmer2010economic]and thus economic growth.

Researchers and policy makers have been highlighting the incredible benefits brought about by Information Technology, integrating modern economies and inevitably affecting economic and industrial growth. Overall, incredibly high expectations have been set on the advancements in ICT, as being a tool for developing and emerging economies to leap frog traditional methods of increased productivity resulting in ICT related positive spillovers (Steinmueller, 2010) and reducing poverty upon increasing productivity and determining economic growth[@world2012world]

However, it is known from time immemorial that everything in life is like the two sides of a coin, with a positive and negative aspect. As a matter of fact, only people who have access to ICT will benefit from it whereas those who do not, will not. Especially for those countries in which ICT investments are scarce, the risk of being marginalized or bypassed becomes even higher. Many scholars and researchers nowadays have been focusing on the topic of digital divide and increased gross inequalities between nations determined by globalized investments in ICT. Aside from its reliance on technology, ICT also requires an absorptive capacity in terms of labor and technical skills, to fully benefit from the investments in ICT infrastructure[@jorgenson1995computers]

