
title: What effect does ICT investment and non-ICY investments have on economic growth in Developed, Emerging and Developing Countris
author: "By Alessia D??? Alessandro and Nitij Singh
Hertie School of Governance
Instructor: Christopher Gandrud
Fall Semester, 2015
11.12.2015"
date: "11 December 2015"
output: pdf_document
bibliography: Biblio.bib
highlight: tango
geometry: margin=3cm
theme: united
toc:yes
toc_depth: 3



# Abstract 
This paper aims at analyzing the validity of the relationship between Information and Communication Technology (ICT) and economic development, expressed in terms of GDP growth. The study provides a cross-country view on the issue upon assessing the impact of ICT on economic growth for 54 countries from the developed, emerging and developing world. Despite various panel regressions from other studies showing a positive relationship between ICT and GDP growth, our results show that even though the impact of ICT capital stock per capita is significant in the developed and emerging economies, it cannot be used to make generalizations for the developing countries. 

# Table of Contents
1. Introduction??????????????????????????????????????????????????????????????????????????????????????????......... 3
2. Literature Review??????????????????????????????????????????????????????????????????????????????????????????.4
3. Data and Datasets??????????????????????????????????????????????????????????????????????????????????????????.5
4. Definition of key concepts and variables???????????????????????????????????????????????????????????????..6
5. Outlier detection and missing values??????????????????????????????????????????????????????..????????????..8
6. Descriptive Statistics ?????????????????????????????????????????????????????????????????????????????????...???9
7. Model??????????????????????????????????????????????????????????????????????????????????????????????????????..10
8. Empirical Results ???...????????????????????????????????????????????????????????????????????????????????????10
9. Visual inspections of the Data ??????.....???????????????????????????????????????????????????????????????..11
10. Limitations of the study ???????????????????????????.????????????????????????????????????????????????..???15
11. Concluding Remarks ??????.???????????????????????????????????????????????????????????????????????????..16
12. Policy Recommendations??????????????????????????????????????????????????????????????????????????????.17
13. Bibliography?????????????????????????????????????????????????????????????????????????????????????????????.18


# Introduction 
The information revolution and the extraordinary increase in the spreading of knowledge have given rise to a new era of knowledge and information, affecting directly economic, social, cultural and political activities of all regions of the world (Ogunsola 2005). 
For years, Information and Communication Technologies (ICT) has been identified as a key driver for improving living standards. These higher living standards often correlate with productivity growth (Timmer et al. 2010)and thus economic growth. 
Given the higher productivity effect, researchers and policy makers have been highlighting the incredible benefits brought about by Information Technology, integrating modern economies and inevitably affecting economic and industrial growth. Overall, incredibly high expectations have been set on the advancements in ICT, as being a tool for developing and emerging economies to leap frog traditional methods of increased productivity resulting in ICT related positive spillovers (Steinmueller, 2010) and reducing poverty upon increasing productivity and determining economic growth (Group 2012). 
However, it is known from time immemorial that everything in life is like the two sides of a coin, with a positive and negative aspect. As a matter of fact, only people who have access to ICT will benefit from it whereas those who do not, will not. Especially for those countries in which ICT investments are scarce, the risk of being marginalized or bypassed becomes even higher. Many scholars and researchers nowadays have been focusing on the topic of digital divide and increased gross inequalities between nations determined by globalized investments in ICT. Aside from its reliance on technology, ICT also requires an absorptive capacity in terms of labor and technical skills, to fully benefit from the investments in ICT infrastructure (Jorgenson and Stiroh 1995). 
Moreover given the limitation of studies of the effective benefits brought about by ICT in developing and emerging markets, it is hard to make generalizations on the actual impact that the mere investment in ICT infrastructure is causing (Pe??a-L??pez et al, 2007). 
The largest effect of increased availability of ICT technology is probably the facility by which members of societies have access to information. In modern times, in a world of increasing gross inequalities between nations, contemporary discourses have been trying to identify forces that could improve countries socio???economic conditions and reduce inequalities between developed and developing countries. However, current debates are being rather critical towards thee actual effect of ICT and are centered on the topic of digital divide, how the globalization of markets has rather harmed emerging and developing economies. 
# Literature Review 
It comes with no doubts that the investment in ICT has had a significant impact on many countries worldwide, affecting the way people learn, work and exchange information. Ever since the advent of computers, government policy advisors and international developing agencies have pointed to the opportunities that technologies open to innovation (Avgerou, 2009). 
For years ICT was also identified as one of the key tools to foster economic development, with a major- ity of studies and panel regressions confirming the positive relationship between ICT Capita and GDP Growth (Cardona, Kretschmer, and Strobel 2013).???This evolving global communication fabric is intelligent, adaptive and highly innovative and its impact can be felt at both the micro and macro economics levels???(World Economic Forum, 2009). 
Several growth accounting studies revealed a significant contribution of ICT on economic performance especially after the year 1990 in developed economies. This effect can be related to the productivity miracle occurring as soon as quality adjusted and the costs for ICT tools started falling. Closer examination on the contribution of ICT to output and productivity growth was initiated by (Oliner and Sichel 2000) and (Jorgenson and Stiroh 1995).Besides the follow-up studies by Jorgenson and Stiroh (2000), and Oliner and Sichel (2001, 2002) for the U.S. economy, the notable studies on individual countries include (Oulton 2002) for the United Kingdom,(Jalava and Pohjola 2001) for Finland, (Van der WIEL and others 2001) and (Khan, Santos, and others 2002) for Canada,(Gordon 2002) for Germany??? and (Cette, Mairesse, and Kocoglu 2000)for France. The significant studies for a group of countries include (Colecchia and Schreyer 2002), Colecchia and Schreyer (2001), Ark et al (2002), and Daveri (2002) for most EU economies; and Jorgenson (2003) for the G7 economies. 
United Nations ICT Taskforce has identified ICT as key tool to enable economic growth in developing countries offering these the unique opportunity to leapfrog certain stages of development by the use of technologies that undergo the traditional stages of progress to the information society (Force, U.I.T., 2003). Moreover, United Nations ICT Taskforce has identified ICT as key tool to enable economic growth in developing countries offering these the unique opportunity to leapfrog certain stages of development by the use of technologies that undergo the traditional stages of progress to the information society (Force, U.I.T., 2003). However, as the listing shows, most of the studies are centered on developed economies, with a scarcity of studies on the emerging and developing countries. This stresses the questionable validity of the effective impact that ICT has on economic development. As a matter of facts, more recently the link between ICT and development has been articulated in the alarming terms of the ??? digital divide???(Avgerou, 2009). 
Many researchers and scholars have argued that globalization has instead determined the possible widening of the gap between the rich and the poor nations, and caused the emerging of the concept of ???digital slavery???(Ogunsola, 2005) Moreover, lacking absorptive capacities such as appropriate levels of human capital or insufficient funding for conducting research and development are all valid factors to consider when studying the effect of ICT in these different country classifications. 
# Data and Datasets 
We analyze the impact of ICT on GDP growth as well as the effect of Non ICT on GDP growth, (i.e. manufacturing and infrastructure). The primary data source for the study was complied from Conference Board Total Economy Database (Growth). Total Economy Database (TED), is an open source database used for the economic and business knowledge collected by the organization ??? The Conference Board???. As secondary dataset we used the World Bank Development Indicator (WDI), especially for the inclusion of observations for the control variables, namely ???Export percentage of GDP??? and ???Population annual percentage growth???. The TED dataset contains annual data for GDP, ICT and non ICT Capital Service and labor services for 123 countries with a timeframe ranging from 1990 to 2013. Due to missing variables in output and capital input, the time series for this study is limited to the years 1995 to 2010. Moreover, the number of countries has been reduced to 56 (19 Developed, 19 Emerging and 18 Developing Countries, randomly selected) with a total of 864 observations. 

# Definition of key concepts and variables 
Developed Countries: 
  While there is no one, set definition we classify developed countries as those with a relatively high level of economic growth and security. Specifically we look at the GDP per capita levels and GNI. When above $ 23000 in 2013, we consider a country developed. 
Developing Countries: 
  We define developing countries as those lacking in terms of its economy, infrastructure and industrial base. We associate low standard of livings and we group under this category all those countries with a GDP/GNI ratio lower than $6500 in 2013. 
Emerging Markets 
Also for emerging markets, there has not been a commonly accepted definition, however we define them as those nations experiencing rapid growth, industrialization and socio economic development. There are 3 aspects underlying the definition of emerging markets: 1) the absolute level of economic development, indicated by the average GDP per capita; 2) the relative pace of economic development, indicated by the GDP growth rate; 3) the system of market governance and the extent and stability of free market systems (Arnold, D. & Quelch, A., 1998) We only focus on point 2, studying the effect that ICT investments have on annual GDP percentage growth. 
GDP 
Defined as an aggregate measure of production. It is the sum of the gross values added of all resident institutional units engaged in production (plus any taxes and minus any subsidies on products not included in the value of their outputs). The sum of the final uses of goods and services (all uses except intermediate consumption) is measured in purchasers??? prices less the value of imports of goods and services, or the sum of primary incomes distributed by resident producer units. Based on the levels of GDP, we have classified countries accordingly 
i)Developed Countries with a GDP per capita in terms of Purchasing Power Parity higher than $23.000 with adjusted value of year 1995 to 2013 US dollars. ii)Emerging Countries with a GDP per capita in terms of Purchasing Power Parity ranging between $23.000 and $6.500 with adjusted value of year 1995 to 2013 US dollars. iii)Developing Countries with a GDP per capita in terms of Purchasing Power Parity lower than $6.5000 with adjusted value of year 1995 to 2013 US dollars. 
GDP Growth 
The sum of the final uses of goods and services are measured in Purchasing Power Parity (PPP) expressed in 2013 U.S dollars. 
Economic Growth 
An increased capacity of an economy to produce goods and services in one period of time compared to a prior time period. It is measured in terms of Gross Domestic Product. Comparison of levels of economic growth between countries is based on levels of GDP per capita. Economic growth is usually associated with technological changes and can thus best reflect the impact of ICT. Past economic growth is key to the material well being of people today. 
ICT 
The acronym ICT stands for Information Communication Technology. We define ICT as the acquisition of equipment and computer software that provide access to information through telecommunication. For the purpose of this study we will only look at 2 communication technologies, the Internet and cell phones as we assume these to be key drivers in the boosting economic growth. 
ICT Capital Services Growth 
Defined as the change in the flow of productive services provided by ICT assets. We focus on three types of ICT assets namely computer hardware and equipment, telecommunication equipment, and computer software and services. The underlying capital stock series are calculated from the investment data using the perpetual inventory method. The aggregation of the growth in capital services over the different asset types is calculated using the user cost approach. 
Non ICT Capital Service Growth 
Refers to the change in the flow of productive services provided by non-ICT assets. Three types of non-ICT assets are included transport equipment; plant, machinery, and other non-ICT equipment; and construction, building and other structures. The underlying capital stock series are calculated from the investment data using the perpetual inventory method. The aggregation of the growth in capital services over the different asset types is calculated using the user cost approach. 
Export percentage of GDP 
The export of goods and services representing the value of all goods and other market services provided to the rest of the world. They include the value of merchandise, freight, insurance, transport, travel, royalties, license fees, and other services, such as communication, construction, financial, information, business, personal, and government services. They exclude compensation of employees and investment income (formerly called factor services) and transfer payments (WDI). In our study this variable was included as a control variable as it can be used as a good first approximation of wellbeing of a country for international and temporal comparison. However, we have to keep in mind that this measure excludes several crucial elements of general wellbeing such as environment conservation, safety, and population literacy rates. 
Population Growth Annual Percentage 
Annual population growth rate for year t is the exponential rate of growth of midyear population from year t-1 to t, expressed as a percentage. Population is based on the de facto definition of population, which counts all residents regardless of legal status or citizenship???except for refugees not permanently settled in the country of asylum, who are generally considered part of the population of the country of origin (WDI). This variable was only included as a control variable and is central for improving statistical robustness. Higher population growth can be reflected in higher levels of active population contributing to the production process and thus higher levels of inputs revealed in economic growth. 
# Outlier Detection and Missing Values
During the visual inspection of the primary data source we identified many breaks in the data series and missing values. Several countries had to be dropped from the cross- country data source. This reduced the number of countries from 123 to 56 and ultimately to 54 countries; countries that had zero investment in ICT were also plunged from the data set. One interesting observation arising upon cleaning the data was that the missing values related to ICT investment were higher in developing countries as compared to developed and emerging countries. This supports the theory of Pe??a-L??pez et al, claiming lacking information for the assessment of the effect of ICT on GDP growth in developing economies.  
# Descriptive Statistics 
Table 1, 2 and 3 reports the descriptive statistics of the all three categories of the countries. In descriptive tables, we have included some other variables example such as labor input, ICT capital and Non capital in order to comprehend the primary data. With regard to the variable GDP growth, we observed that developing countries registered the highest levels of GDP growth i.e 4.8 points, as compared to developed countries, which have GDP growth of only 2.307. At this point, it is important to keep in mind that higher levels of GDP do not necessarily correspond with higher levels of development. If we take the case of India for instance, they have much higher levels of GDP than New Zealand or Belgium, but few would suggest that the latter are economically less developed than the former. Moreover, the lower levels of GDP growth in the developed world could be explained by the rampant economic recession (2008) affecting financial markets. 
If we observe the mean contribution of ICT in GDP growth among all the three categories we cannot derive any concluding remarks and therefore required a further analysis of the preliminary data. In further analysis we tried to understand the driving force behind the GDP growth upon including control variables namely ???Export percentage of GDP??? and ???Population Percentage Growth???. Upon including the aforementioned variables and conducting lagged OLS regression, we were surprised by the results showing that the variable ???Export percentage of GDP??? is highest in emerging countries (we would have expected the highest level for developing countries if we take the previous results into consideration since openness to trade should be correlated with GDP growth rates) so that we can claim that emerging economies, even if not facing the highest GDP growth, are more export oriented markets and open to trade. 

# Model 
In order to understand the impact of ICT, a regression output can reveal the difference in effects among different economies. As our primary data source was a time series data on GDP growth, ICT capital service growth and Non-ICT capital service growth. In the time series data we obtained multiple variables captured over time in a given country. Through these variables we wanted to understand the effect of ICT and Non-ICT on GDP growth therefore we defined these as independent and dependent variables respectively. We used a dynamic econometric model with lagged independent variables. 

In a lagged econometric model the dependent variable does not react fully to a change in independent variable(s) during the period in which the change occurs therefore the model captures the relationship at time t and lagged relationship at time t-1. Similarly in our model captures the lagged relation between GDP growth and ICT and Non-ICT contribution. 
The most common issues with lagged econometric model are multicollinearity and heterogeneity. In order to minimize the effect of multicollinearity, the independent variables used in our model were not correlated, as one variable cannot linearly predict the other. The additional variable such as??? Exports percent in total GDP??? controls heterogeneity as export coefficients clearly positive and significant to GDP growth. 
# Empirical Results Developed Countries 
Once the data was arranged the dependent variable (GDP growth) was regressed with the independent variables (ICT and Non-ICT capital growth)(Table 4). Initially when no control variables were applied in the model, ICT capital growth and Non ICT capital growth both had significant impact on GDP growth. In the next step when control variables were included in the model, ICT and Non-ICT capital growth still remained significant yet the coefficient of ICT reduced. This reduction in the coefficient of ICT capital growth explains the variation in GDP growth caused by the control variables. 
However as the regression table highlights, ICT capital growth does play a significant role in levels of GDP growth in developed countries. On the contrary the control variables ???Export Percentage of GDP??? and ???Population Percentage Growth??? have no significant impact on GDP growth in developed economies. 
# Empirical Results Emerging Countries 
Emerging countries showed similar results to developed economies, with ICT and Non-ICT capital service having a significant impact on GDP growth. Even when control variables were applied, the dependent variable showed significant results. In emerging countries, population growth was more significant when compared to developed countries; therefore from the table we can state that one unit increase in population growth causes 0.387 GDP growth. Overall we had similar results for developed and emerging countries where ICT capital growth played impact in economic development of the economies. 
# Empirical Results Developing Countries 
The results among developing countries were slightly reversed from the results we have seen above. In developing countries, ICT capital growth had no significant impact on GDP growth whereas non-ICT capital growth did have a significant one. Non-ICT capital growth had positive impact on GDP (i.e one unit increase in Non-ICT capital caused 0.641 percentage GDP growth}. Among the control variables, ???Population % Growth??? was highly significant yet had a negative relationship; As the output from the table displays, it is possible to claim that one unit increase in ???Population % Growth ???decreases GDP growth by 0.845 percentage points. 
# Visual Inspection of the Data 
In order to comprehend the data further we created some visual graphics for all the three categories of countries by using R-Plot. In the diagram below we observe that there is limited variation in developed countries when ICT capital growth is observed over the time period from 1995-2010. With the help of the plot below we were able to detect some developing countries, which had phenomenal ICT growth, such as Sri Lanka. The categories 1, 2 and 3 in the plot represent developed, developing and emerging countries respectively. 
As in the paper we wanted to understand the difference in impact of ICT capital and Non ICT capital therefore it was highly essential to segregate the information on that basis. In order to understand the difference in impact we created a bar chart using googleVis. The bar chart explains the contribution of ICT and Non ICT capital for the year 2009 and GDP growth for the year 2010. We can observe that Non-ICT capital is higher in developing countries; the reason could be that these economies majorly depend on manufacturing or labor intense jobs. In developed the difference between ICT capital growth and Non ICT capital is almost negligible. 

In order to understand the growth of ICT capital services among individual categories of the countries; we used ggplot methodology. 
# Developed Countries 
The diagram below shows the trend of ICT capital growth among selected developing countries. Overall we observe a downward trend among developing countries leaving out certain outliers such as Denmark and Italy which experienced increase in ICT capital growth in the year 2010. 

# Emerging Countries 
In the case of emerging countries we observe a mix trend with regards to ICT capital growth. Certain countries have observed a steady increase in ICT capital like Costa Rica and Slovenia. Some countries have shown a stable trend Mexico, Poland and Portugal. Other countries showed irregularities in their trends with sudden rise and fall, maybe recession during the time period of 2007-2009 had some impact on the ICT capital. In many discussions it has been pointed out that Brazil, South Africa, Turkey and Mexico are the emerging economies and if we observe the diagram below we find that ICT growth is positive among all these countries. Therefore ICT capital has some significance in emerging economies. 


# Developing Countries 
The empirical results derived above show that ICT capital growth was insignificant in developing countries. Visual analysis of the ICT capital growth augments our results because the graph shows linear trends among all the countries leaving some outliers like Sri Lanka and Nigeria.


# Google Vis
Below, our study includes an interactive visualization of the impact of ICT in all countries (Developed, Emerging and Developing) based on figures from 2010. Visualization can help the reader to better contextualize the quantitative results provided by our study. In the maps below, stronger effects are correlated with darker colors.  
# Limitations of the study
One of the key limitations that our study presents is the lack of available data explaining the impact of ICT in developing and emerging markets (as claimed in the literature review). The limited number of observations and of years covered that our analysis presents might create some general measurement issues, impeding us to make any generalizations, undermining the external validity of our test. The selected sample of countries being analyzed does not allow for proper randomization and thus we might be encountering some sample selection bias effect, with the sample obtained being not representative of the population being analyzed. Moreover, the limitation of our study on the mere effect of ICT contribution and non-ICT contribution to explain economic growth does not fully constitute an answer to what is attracting ICT investments. Other factors such as social development indicators (government effectiveness, political stability, unemployment rate) educational indicators (enrolment rates in primary, secondary and tertiary education), additional economic indicators (current account balance, real interest rates, trade balance, total investment, government revenues etc.), demographic indicators and technological indicators, should have been taken into account to make the sample of the study more representative. 
# Concluding remarks 
Despite having ICT often referred to as a catalyst for innovation and modernization, lowering transaction costs, blurring boundaries and spreading information that will make societies better off, our findings demonstrate its empirical limitations. The conclusion of this study is that certain steps need to be undertaken in order to access the full benefits that ICT can determine. Since the early 1990, international institutions have been pushing developing nations to deregulate and heavily invest in ICT infrastructure as a strategy for accelerating socio economic development (Ngwenyama & Morawczynski, 2010). However, after more than a decade of continuous investments, some countries still have not achieved the desired outcomes. Our findings demonstrate that simply mastering technology is not enough for determining economic development in the absence of complementary factors. When presenting the results for the levels of GDP, ICT Contribution and Non ICT Contribution, it became evident that especially in those countries experiencing the highest levels of GDP Growth (surprisingly the developing countries and not the emerging economies) the role played by ICT Contribution was really marginal, and lower than the contribution of Non ICT factors meaning that it is not possible to claim a positive effect of ICT infrastructure levels on GDP growth. The results of this paper call for more empirical research to assess the performance and impact of ICT in developing and emerging countries and argues that policy makers need to cultivate other conditions such as human labor capacity and technical skill levels to enable emerging and developing economies to fully benefit from ICT investments. ??? If developing countries are to seize the opportunities of technological innovation (. . . ) they will have to harness those innovation and the knowledge that comes with them??? (UNCTAD, 2007). 
# Policy recommendations
As the study has shown, it is difficult to assess the impact of ICT on GDP growth. However we believe that higher investments in ICT infrastructure can still help developing and emerging countries to reach higher economic performance.
In view of this, in this section, we turn our attention to the policy tools necessary to promote ICT investments in order to benefit the most from ICT potential to contribute to economic growth. 
In our view, policy tools required to stimulate the deployment of ICT infrastructure ranges from the formulation of national ICT plans and government intervention to correction of some of the market failures making investments in these countries less attractive.
More specifically we believe that the following broad policy areas should be considered: 
  
  ???	Investment in promotion of adoption programs:  More specifically, the implementation of supply oriented policies to  promote the adoption of IC and IT by certain social groups and firms that may not be naturally inclined to adopt the technology. This could be done via increasing digital literacy, providing economic incentives and subsides and the development of E-Government, facilitating the interaction between citizens and governments or businesses and governance.
???	Provide explicit incentives for ICT: such as tax incentives and include some evaluation programs to identify the impact of ICT on productivity and other factors over the years (historical approach). The question to be answered is whether the lesson from ICT can be applied to future types of technical change, in other words, what lessons form past waves of technical change can be applied to ICT. This can only be achieved upon collecting results over longer time periods.
???	Invest in technological skills, if governments want to enable a significant part of the population to enjoy the benefit related to ICT.
???	Adoption of competition policy: as competition might be stimulating the ICT supply, explicitly or implicitly.
???	Removal of any potential supply obstacles: lowering economic barriers to entry for international investors
???	ICT in the public sector: ICT has the great potential to also generate large productivity growth in the public sector, such as with the computerization of hospitals, schools, police etc. In view of this, it can be extremely valuable for policymakers to make the public sector work more effectively and efficiently. 

# Bibliography 
Cardona, Melisande, Tobias Kretschmer, and Thomas Strobel. 2013. ???ICT and Productivity: 
  Colecchia, Alessandra, and Paul Schreyer. 2002. ???ICT Investment and Economic Growth in the 1990s: Is the United States a Unique Case?: A Comparative Study of Nine OECD Countries.??? Review of Economic Dynamics 5 (2). Elsevier: 408???42. 
Gordon, Robert J. 2002. ???New Economy???An Assessment from a German Viewpoint.??? RWI-Studie Im Auftrag Des Bundesministeriums F??r Wirtschaft Und Forschung, Erscheint Demn??chst. 
Group, World Bank. 2012. World Development Indicators 2012. World Bank Publications.(Growth, Groningen. ???Development Centre and the Conference Board (2004), Total Economy Database.??? 
Jalava, Jukka, and Matti Pohjola. 2001. ???Economic Growth in the New Economy.??? UNU/WIDER Discussion Paper, no. 2001/5. 
Jorgenson, Dale W, and Kevin Stiroh. 1995. ???Computers and Growth.??? Economics of Innovation and New Technology 3 (3-4). Taylor & Francis: 295???316. 
Khan, Hashmat, Marjorie Santos, and others. 2002. Contribution of ICT Use to Output and Labour- Productivity Growth in Canada. Bank of Canada. 
Ogunsola, LA. 2005. ???Information and Communication Technologies and the Effects of Globalization: Twenty- First Century ???Digital Slavery??? for Developing Countries???Myth or Reality.??? Electronic Journal of Academic and Special Librarianship 6 (1-2): 1???10. 
Oliner, Stephen D, and Daniel E Sichel. 2000. ???The Resurgence of Growth in the Late 1990s: Is Information Technology the Story???? FEDS Working Paper. 
Oulton, Nicholas. 2002. ???ICT and Productivity Growth in the United Kingdom.??? Oxford Review of Economic Policy 18 (3). Oxford Univ Press: 363???79. 
Pe??a-L??pez, Ismael, and others. 2007. ???Information Economy Report 2007-2008: Science and Technology for Development: The New Paradigm of ICT.??? UNCTAD. 
Timmer, Marcel P, Robert Inklaar, Mary O???Mahony, and Bart Van Ark. 2010. Economic Growth in Europe: A Comparative Industry Perspective. Cambridge University Press. 
Van der WIEL, Henry, and others. 2001. Does ICT Boost Dutch Productivity Growth? CPB Netherlands Bureau for Economic Policy Analysis. 

