---
title: "test2"
author: "Nitij"
date: "22 October 2015"
output: html_document
bibliography: Biblio.bib
---

Brazil, Russia, India, China and South Africa form a conglomerate of the world´s fastest economies acting as major engines of global growth. What role did ICT developments play in the exponential boom of these nations and to what extend did investments in ICT determine this unprecedented economic growth?

Nowadays, communication and information technologies (ICT) are an essential tool in every society and economy, transforming ways social and personal interaction happens, enabling global cooperation between businesses trough “The Internet of Things”, bustling industries, spurred by entrepreneurship and supported by a variety of multinational enterprises and helping governments to broaden citizen services and improving their delivery. 
The pace, at which countries outside of the advanced economies are adopting the Internet, is much faster than that of advanced economies[@nottebohm2012online].According to a study conducted by BCG, by 2016, there will be 3 billion Internet users globally, almost half of the world’s population. The Internet economy will reach 4.2 trillion dollars in the G-20 countries[@dean2012internet].

#Reference
